server:
  port: 5001

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_location_db
    username: root
    password : Kvishwash@2001


  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update